[bridge]
port = 8080

[sensors]
query_interval = 1000

[sensors.neurio]
host = "neurio.local"
device_model = "PWRview"

[mqtt]
proto = "mqtt"
host = "mqtt.local"
port = 1883
user = ""
password = ""
topic = "neurio"

[homeassistant]
discovery_topic = "homeassistant"
